### ISSUE TITLE
Error in calculations

### ISSUE THREAD

**Issue by mg901** [oddbird/accoutrement-scale#5]
```
$ratios: (
  'my-ratio': 1.25,
);

$sizes: (
  'root': 16px ,
  'line-height': 1.6,
  'rhythm': 'root' ('fifth': 1, 'convert-units': 'rem'),

  'h1': 'root' ('my-ratio': 6, 'convert-units': 'rem'),
  'h2': 'root' ('my-ratio': 5, 'convert-units': 'rem'),
  'h3': 'root' ('my-ratio': 4, 'convert-units': 'rem'),
  'h4': 'root' ('my-ratio': 3, 'convert-units': 'rem'),
  'h5': 'root' ('my-ratio': 2, 'convert-units': 'rem'),
  'h6': 'root' ('my-ratio': 1, 'convert-units': 'rem'),

  'page': '8in',
);

.section {
  max-width: size('page');
}
```

Error: 8in is not a valid length for CSS.
        on line 45 of node_modules/accoutrement-scale/sass/_size.scss
>>     @error '#{$size} is not a valid length for CSS.';
   ----^

**Comment by mirisuzanne** [comment]
You should unquote actual length values. The quotes turn it into a string.

**Comment by mg901** [comment]
So this is a bug about the [documentation](http://joxi.ru/Vrwqz5qUO54xq2).  Style guide section. Thank you very much for your answer.

**Comment by mirisuzanne** [comment]
oops! Want to submit a PR for that?

**Comment by mg901** [comment]
What is PR?)))

**Comment by mg901** [comment]
If you offer to help you correct mistakes in the documentation, then I will be only glad.

**Comment by mirisuzanne** [comment]
A Pull Request? Correct the documentation on your fork, and then submit them for merging into the main branch?
